spin_manifest_version = 2

[application]
name = "challenge3"
version = "0.1.0"
authors = ["jessai <maya.jessai@gmail.com>"]
description = ""

[[trigger.http]]
route = "/api/..."
component = "challenge3"

[component.challenge3]
source = "target/wasm32-wasi/release/challenge3.wasm"
allowed_outbound_hosts = ["http://127.0.0.1:3000"]
sqlite_databases = ["default"]
files = ["list.txt"]

[component.challenge3.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]
