[package]
name = "challenge2"
authors = ["jessai <maya.jessai@gmail.com>"]
description = ""
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde_json = "1.0.122"
anyhow = "1"
serde = { version = "1.0.204", features = ["derive"] }
spin-sdk = "3.0.1"

[workspace]
